stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/data_ingestion_pipeline.py
    deps: 
      - src/cnnClassifier/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney_tumor_classificaiton_dataset

  prepare_base_model:
    cmd: python src/cnnClassifier/components/base_model_preparation.py
    deps: 
      - src/cnnClassifier/components/base_model_preparation.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/cnnClassifier/pipeline/model_training_pipeline.py
    deps:
      - src/cnnClassifier/components/model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney_tumor_classificaiton_dataset
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/cnnClassifier/components/model_evaluation.py
    deps:
      - src/cnnClassifier/components/model_evaluation.py
      - artifacts/training/model.h5
      - artifacts/data_ingestion/kidney_tumor_classificaiton_dataset
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:

      - scores.json:
          cache: False
